permalink: /:year:month:day/:title
url: https://josh-tf.github.io/
baseurl: /project

# variables
name: josh-tf | personal website
description: Developer, Analyst and Nerd from Melbourne, AU
google_verification: null


# File management
include: [".htaccess"]
exclude: ["README.md", "LICENSE"]

# Sass
sass:
  style: :compressed
  sass_dir: _sass

# Markdown
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter_opts:
    disable : true
